const LinkImportService = require('../services/LinkImportService');
const { getPool } = require('../../lib/postgres');
const { currentUserId, isAdmin } = require('../middleware/accountOwnership');

class LinkImportController {
  async import(req, res) {
    try { const result = await LinkImportService.importFile({ accountId: req.body.accountId, fileName: req.body.fileName, content: req.body.content, encoding: req.body.encoding || 'text', importPolicy: req.body.importPolicy || 'ignore_duplicates', sourceType: req.body.sourceType || 'file' }); res.json({ success: true, ...result }); }
    catch (e) { res.status(400).json({ success: false, error: e.message }); }
  }
  async files(req, res) { try { res.json({ success: true, files: await LinkImportService.listFiles(req.query.accountId) }); } catch (e) { res.status(500).json({ success: false, error: e.message }); } }
  async file(req, res) { try { res.json({ success: true, ...(await LinkImportService.getFile(req.query.accountId, req.params.fileId)) }); } catch (e) { res.status(500).json({ success: false, error: e.message }); } }
  async reprocess(req, res) { try { res.json({ success: true, ...(await LinkImportService.reprocessFile(req.body.accountId || req.query.accountId, req.params.fileId)) }); } catch (e) { res.status(400).json({ success: false, error: e.message }); } }
  async accounts(req, res) { try { const userId = currentUserId(req); const sql = isAdmin(req) ? 'SELECT id,name,phone_number,status,health_status,connection_type,last_activity_at FROM accounts ORDER BY created_at DESC' : 'SELECT id,name,phone_number,status,health_status,connection_type,last_activity_at FROM accounts WHERE user_id=$1 ORDER BY created_at DESC'; const r = await getPool().query(sql, isAdmin(req) ? [] : [userId]); res.json({ success: true, accounts: r.rows.map(a => ({ ...a, connected: require('../../bot/WhatsAppManager').isReady(a.id) })) }); } catch (e) { res.status(500).json({ success: false, error: e.message }); } }
  async start(req, res) { try { res.json({ success: true, job: await LinkImportService.start(req.body) }); } catch (e) { res.status(400).json({ success: false, error: e.message }); } }
  async jobs(req, res) { try { res.json({ success: true, jobs: await LinkImportService.listJobs(req.query.accountId) }); } catch (e) { res.status(500).json({ success: false, error: e.message }); } }
  async job(req, res) { try { const details = await LinkImportService.getJobDetails(req.query.accountId, req.params.jobId); res.json({ success: !!details, ...(details || { job: null }) }); } catch (e) { res.status(500).json({ success: false, error: e.message }); } }
  async control(req, res) { try { const fn = { pause: 'pause', resume: 'resume', stop: 'stop', cancel: 'cancel', retry: 'retry', restart: 'restart' }[req.params.action]; if (!fn) throw new Error('إجراء غير صالح'); res.json({ success: true, job: await LinkImportService[fn](req.body.accountId, req.params.jobId) }); } catch (e) { res.status(400).json({ success: false, error: e.message, code: 'LINK_IMPORT_ACTION_FAILED' }); } }
  async settings(req, res) { try { const accountId = req.query.accountId || req.body.accountId; if (!accountId) throw new Error('معرف الحساب مطلوب'); const db = await require('../../database/DatabaseManager').getAccountDB(accountId); const result = await db.query('SELECT settings,updated_at FROM link_import_settings WHERE id=1'); const defaults = { minDelay: 30, maxDelay: 60, maxAttempts: 3, distributionMode: 'smart', executionMode: 'full_file_per_account' }; const saved = result.rows[0]?.settings || {}; res.json({ success: true, settings: { ...defaults, ...saved }, updatedAt: result.rows[0]?.updated_at || null }); } catch (e) { res.status(500).json({ success: false, error: e.message }); } }
  async pauseAccount(req, res) { try { const row = await LinkImportService.pauseAccount(req.body.accountId, req.params.jobId, req.params.targetAccountId); res.json({ success: true, account: row }); } catch (e) { res.status(400).json({ success: false, error: e.message }); } }
  async resumeAccount(req, res) { try { const row = await LinkImportService.resumeAccount(req.body.accountId, req.params.jobId, req.params.targetAccountId); res.json({ success: true, account: row }); } catch (e) { res.status(400).json({ success: false, error: e.message }); } }
  async saveSettings(req, res) { try { const accountId = req.body.accountId; if (!accountId) throw new Error('معرف الحساب مطلوب'); const minDelay = Math.max(0, Number(req.body.minDelay) || 0); const maxDelay = Math.max(minDelay, Number(req.body.maxDelay) || minDelay); const maxAttempts = Math.min(10, Math.max(1, Number(req.body.maxAttempts) || 1)); const distributionMode = ['round_robin', 'smart', 'least_loaded'].includes(req.body.distributionMode) ? req.body.distributionMode : 'smart'; const settings = { minDelay, maxDelay, maxAttempts, distributionMode, executionMode: 'full_file_per_account' }; const db = await require('../../database/DatabaseManager').getAccountDB(accountId); const saved = await db.query("INSERT INTO link_import_settings(id,settings,updated_at) VALUES(1,$1,NOW()) ON CONFLICT(id) DO UPDATE SET settings=EXCLUDED.settings,updated_at=NOW() RETURNING settings,updated_at", [JSON.stringify(settings)]); res.json({ success: true, settings: saved.rows[0].settings, updatedAt: saved.rows[0].updated_at }); } catch (e) { res.status(400).json({ success: false, error: e.message }); } }
}

module.exports = new LinkImportController();
