import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { io, Socket } from 'socket.io-client';
import { Search, Play, Pause, Square, RefreshCw, Settings, Users, Link2, Copy, ExternalLink, Activity, Bell, CheckCircle2, XCircle } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { API, authFetch } from '@/utils/api';

type Account = { id:string; name:string; phone_number?:string; connected:boolean; status?:string };
type Job = { id:string; status:string; selected_account_ids:any; groups_discovered:number; groups_scanned:number; messages_processed:number; links_total:number; links_new:number; links_copied:number; links_duplicate:number; links_invalid:number; started_at?:string; last_scan_at?:string; last_activity_at?:string; last_link_at?:string; last_activity_message?:string; last_error?:string };
const statusText:Record<string,string>={running:'يعمل',waiting:'في الانتظار',paused:'متوقف مؤقتاً',stopped:'متوقف',error:'به خطأ',idle:'جاهز',scanning:'جاري الفحص',reconnect:'إعادة اتصال',offline:'غير متصل',new:'جديد',copied:'تم نسخه',duplicate:'مكرر',invalid:'غير صالح',new_link:'رابط جديد',group_scanned:'فحص مجموعة',started:'بدأ البحث'};
const typeText:Record<string,string>={whatsapp_group_public:'🟢 مجموعة واتساب',whatsapp_group_request:'🟡 مجموعة طلب انضمام',whatsapp_channel:'🔵 قناة واتساب'};
const showStatus=(s:any)=>statusText[String(s||'')]||String(s||'غير معروف');
const value=(v:any, fallback='—')=>v===null||v===undefined||v===''?fallback:String(v);

export default function AutoSearchView({accountId,accounts:initialAccounts}:{accountId:string|null;accounts:Account[]}){
 const [accounts,setAccounts]=useState<Account[]>(initialAccounts); const [selected,setSelected]=useState<string[]>([]); const [job,setJob]=useState<Job|null>(null); const [links,setLinks]=useState<any[]>([]); const [states,setStates]=useState<any[]>([]); const [groups,setGroups]=useState<any[]>([]); const [events,setEvents]=useState<any[]>([]); const [runtime,setRuntime]=useState<any>({running:false}); const [settings,setSettings]=useState<any>({scope:'all',linkTypes:['whatsapp_group_public','whatsapp_group_request','whatsapp_channel'],removeSpaces:true,normalize:true,removeDuplicates:true,validate:true}); const [filter,setFilter]=useState('new'); const [q,setQ]=useState(''); const [message,setMessage]=useState(''); const [socketState,setSocketState]=useState('offline'); const [now,setNow]=useState(Date.now()); const socket=useRef<Socket|null>(null); const lastEventId=useRef<any>(null);
 const load=useCallback(async()=>{if(!accountId)return;try{const [d,a]=await Promise.all([authFetch(`${API}/auto-search/dashboard?accountId=${accountId}`),authFetch(`${API}/auto-search/accounts`)]);const data=await d.json();const ad=await a.json();if(data.success){setJob(data.job);setRuntime(data.runtime||{running:false});setLinks(Array.isArray(data.links)?data.links:[]);setStates(Array.isArray(data.accounts)?data.accounts:[]);setGroups(Array.isArray(data.groups)?data.groups:[]);setEvents(Array.isArray(data.events)?data.events:[]);setSettings(data.settings||settings);if(data.job&&!selected.length){const ids=Array.isArray(data.job.selected_account_ids)?data.job.selected_account_ids:JSON.parse(data.job.selected_account_ids||'[]');setSelected(ids)}}if(ad.success)setAccounts(ad.accounts||[])}catch(e){setMessage('تعذر تحميل حالة البحث')}} , [accountId]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!accountId)return;const id=setInterval(load,5000);return()=>clearInterval(id)},[accountId,load]);
 useEffect(()=>{if(!job?.id)return;const s=io(window.location.origin,{path:'/socket.io',transports:['websocket','polling'],reconnection:true});socket.current=s;const join=()=>{setSocketState('connected');s.emit('join',`auto-search:${job.id}`)};s.on('connect',join);s.on('disconnect',()=>setSocketState('reconnecting'));s.on('auto_search:update',(p:any)=>{if(p.job)setJob(p.job);if(p.runtime)setRuntime(p.runtime);if(Array.isArray(p.links))setLinks(p.links);if(Array.isArray(p.accounts))setStates(p.accounts);if(Array.isArray(p.groups))setGroups(p.groups);if(Array.isArray(p.events)){setEvents(p.events);const newest=p.events[0];if(newest&&newest.id!==lastEventId.current){lastEventId.current=newest.id;if(newest.event_type==='new_link'){setMessage('🔔 تم اكتشاف رابط واتساب جديد');if('Notification' in window&&Notification.permission==='granted')new Notification('رابط واتساب جديد',{body:newest.message})}}}});return()=>{s.disconnect();socket.current=null}},[job?.id]);
 const action=async(path:string,body:any={})=>{try{const r=await authFetch(`${API}/auto-search/${path}`,{method:'POST',body:JSON.stringify({accountId,...body})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'فشل الإجراء');if(d.job)setJob(d.job);if(d.links)setLinks(d.links);setMessage('تم تنفيذ الإجراء بنجاح');load()}catch(e:any){setMessage(e.message||'تعذر تنفيذ الإجراء')}};
 const start=()=>{if('Notification' in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});return action('start',{accountIds:selected,settings})};
 const visible=useMemo(()=>links.filter(x=>(filter==='all'||x.status===filter)&&(!q||`${x.normalized_url} ${x.source_group_name} ${x.discovered_by_account}`.toLowerCase().includes(q.toLowerCase()))),[links,filter,q]);
 const selectedStates=states.filter(x=>selected.includes(String(x.account_id))); const workerActive=Boolean(runtime.running)&&Boolean(job&&['running','waiting'].includes(job.status)); const total=job?.links_total||0; const lastActivity=job?.last_activity_at?Math.max(0,Math.floor((now-new Date(job.last_activity_at).getTime())/1000)):null; const processed=(job?.links_new||0)+(job?.links_duplicate||0)+(job?.links_invalid||0); const pct=total?Math.round(processed/total*100):0;
 return <div dir="rtl" className="p-5 md:p-8 space-y-5 max-w-[1600px] mx-auto"><div className="flex flex-wrap justify-between gap-4"><div><div className="flex items-center gap-3"><div className="rounded-2xl bg-cyan-500/15 p-3 text-cyan-400"><Search/></div><div><h1 className="text-2xl font-extrabold">البحث التلقائي</h1><p className="text-sm text-[var(--text-muted)] mt-1">اكتشاف روابط المجموعات من الحسابات المحددة مع تشغيل خلفي مستقل</p></div></div></div><div className="flex flex-wrap gap-2"><Button onClick={start} disabled={!!job&&['running','waiting','paused'].includes(job.status)||!selected.length}><Play className="w-4 h-4 ml-2"/>تشغيل البحث</Button><Button variant="outline" onClick={()=>action(job?.status==='paused'?'resume':'pause')} disabled={!job||!['running','waiting','paused'].includes(job.status)}><Pause className="w-4 h-4 ml-2"/>{job?.status==='paused'?'استئناف':'إيقاف مؤقت'}</Button><Button variant="outline" onClick={()=>action('stop')} disabled={!job||job.status==='stopped'}><Square className="w-4 h-4 ml-2"/>إيقاف</Button><Button variant="outline" onClick={()=>action('scan-now')} disabled={!job}><RefreshCw className="w-4 h-4 ml-2"/>فحص الآن</Button><Button variant="outline" onClick={()=>document.getElementById('auto-activity')?.scrollIntoView({behavior:'smooth'})}><Activity className="w-4 h-4 ml-2"/>النشاط المباشر</Button><Button variant="outline" onClick={()=>document.getElementById('auto-stats')?.scrollIntoView({behavior:'smooth'})}>📊 الإحصائيات</Button></div></div>
 {message&&<div className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-3 text-sm">{message}</div>}
 <Card className={workerActive?'border-emerald-500/50':'border-red-500/40'}><CardContent className="p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-lg font-extrabold"><span className={`inline-block w-3 h-3 rounded-full ${workerActive?'bg-emerald-400 animate-pulse':'bg-red-400'}`}/>{workerActive?'🔎 البحث التلقائي يعمل':'🔴 البحث التلقائي متوقف'}</div><p className="text-sm text-[var(--text-muted)] mt-2">{workerActive?'⚡ مراقبة روابط واتساب لحظياً عبر Worker مستقل':'شغّل البحث لبدء المراقبة الخلفية'}</p></div><div className="text-left text-sm"><div>{workerActive?'🟢 ● مراقبة مباشرة':'⚠️ يحتاج إلى تشغيل'}</div><div className="text-[var(--text-muted)] mt-1">آخر نشاط: {lastActivity===null?'—':lastActivity===0?'الآن':`منذ ${lastActivity} ثانية`}</div></div></div></CardContent></Card>
 <div id="auto-stats" className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3">{[['الحالة',workerActive?'يعمل':'متوقف'],['الحسابات',selected.length],['المجموعات',job?.groups_discovered||groups.length],['الرسائل المعالجة',job?.messages_processed||0],['الروابط المكتشفة',total],['الجديدة',job?.links_new||0],['المكررة',job?.links_duplicate||0],['المنسوخة',job?.links_copied||0],['غير الصالحة',job?.links_invalid||0]].map(([l,v]:any)=><Card key={l}><CardContent className="p-4"><div className="text-xs text-[var(--text-muted)]">{l}</div><div className="text-xl font-bold mt-2">{v}</div></CardContent></Card>)}</div>
 <Card id="auto-settings"><CardContent className="p-5"><div className="flex flex-wrap justify-between items-center gap-3"><h2 className="font-bold flex gap-2 items-center"><Settings className="w-5 h-5 text-cyan-400"/>إعدادات البحث</h2><Button variant="outline" onClick={()=>action('settings',{settings})}>حفظ الإعدادات</Button></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-3 mt-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={settings.removeSpaces!==false} onChange={e=>setSettings((s:any)=>({...s,removeSpaces:e.target.checked}))}/>إزالة المسافات</label><label className="flex items-center gap-2"><input type="checkbox" checked={settings.normalize!==false} onChange={e=>setSettings((s:any)=>({...s,normalize:e.target.checked}))}/>توحيد صيغة الرابط</label><label className="flex items-center gap-2"><input type="checkbox" checked={settings.removeDuplicates!==false} onChange={e=>setSettings((s:any)=>({...s,removeDuplicates:e.target.checked}))}/>منع التكرار</label><label className="flex items-center gap-2"><input type="checkbox" checked={settings.validate!==false} onChange={e=>setSettings((s:any)=>({...s,validate:e.target.checked}))}/>التحقق من الرابط</label></div></CardContent></Card>
 <div className="grid xl:grid-cols-[1fr_1.5fr] gap-5"><Card><CardContent className="p-5"><div className="flex justify-between items-center mb-4"><h2 className="font-bold flex gap-2 items-center"><Users className="w-5 h-5 text-cyan-400"/>الحسابات المستخدمة</h2><Badge>{socketState==='connected'?'متصل لحظياً':'إعادة الاتصال'}</Badge></div><div className="flex gap-2 mb-3"><Button variant="outline" onClick={()=>setSelected(accounts.filter(a=>a.connected).map(a=>a.id))}>تحديد المتصل</Button><Button variant="outline" onClick={()=>setSelected([])}>إلغاء الكل</Button></div><div className="space-y-2 max-h-80 overflow-auto">{accounts.map(a=><label key={a.id} className={`flex items-center gap-3 p-3 rounded-xl border ${a.connected?'cursor-pointer':'opacity-50'}`}><input type="checkbox" disabled={!a.connected} checked={selected.includes(a.id)} onChange={e=>setSelected(x=>e.target.checked?[...x,a.id]:x.filter(id=>id!==a.id))}/><span className={`w-2 h-2 rounded-full ${a.connected?'bg-emerald-400':'bg-red-400'}`}/><span className="flex-1"><b>{a.name||a.id}</b><small className="block text-xs text-[var(--text-muted)]">{a.phone_number||'رقم مخفي'} · {a.connected?'متصل':'غير متصل'}</small></span><span className="text-xs">{showStatus(states.find(s=>String(s.account_id)===String(a.id))?.status|| (a.connected?'idle':'offline'))}</span></label>)}</div></CardContent></Card><Card><CardContent className="p-5"><div className="flex justify-between"><h2 className="font-bold">الإحصائيات الحقيقية</h2><Settings className="w-5 h-5 text-cyan-400"/></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">{[['الجديدة',job?.links_new||0],['المكررة',job?.links_duplicate||0],['غير الصالحة',job?.links_invalid||0],['المتبقية',Math.max(0,total-processed)]].map(([l,v]:any)=><div key={l} className="rounded-xl bg-[var(--bg-elevated)] p-3"><div className="text-xs text-[var(--text-muted)]">{l}</div><div className="text-2xl font-bold mt-1">{v}</div></div>)}</div><div className="mt-5"><div className="flex justify-between text-xs mb-2"><span>نسبة الإنجاز الحقيقية</span><b>{pct}%</b></div><div className="h-2 rounded-full bg-[var(--bg-elevated)] overflow-hidden"><div className="h-full bg-cyan-500" style={{width:`${pct}%`}}/></div></div><div className="mt-4 text-xs text-[var(--text-muted)]">آخر فحص: {job?.last_scan_at?new Date(job.last_scan_at).toLocaleString('ar'):'لم يبدأ بعد'}</div></CardContent></Card></div>
 <div className="grid xl:grid-cols-[1.6fr_1fr] gap-5"><Card><CardContent className="p-5"><div className="flex flex-wrap justify-between gap-3 mb-4"><h2 className="font-bold flex gap-2 items-center"><Link2 className="w-5 h-5 text-cyan-400"/>الروابط المكتشفة</h2><div className="flex gap-2"><input className="rounded-lg bg-[var(--bg-elevated)] px-3 py-2 text-sm" placeholder="البحث في الروابط..." value={q} onChange={e=>setQ(e.target.value)}/><Button onClick={()=>action('copy',{filter:filter==='all'?'new':filter})} disabled={!visible.length}><Copy className="w-4 h-4 ml-2"/>نسخ الكل</Button></div></div><div className="flex gap-2 flex-wrap mb-4">{[['all','الكل'],['new','جديدة'],['copied','منسوخة'],['duplicate','مكررة'],['invalid','غير صالحة']].map(([k,l])=><Button key={k} variant={filter===k?'default':'outline'} onClick={()=>setFilter(k)}>{l}</Button>)}</div><div className="overflow-auto max-h-[520px]"><table className="w-full text-sm"><thead><tr className="text-right text-[var(--text-muted)] border-b border-[var(--border-default)]"><th className="p-2">الرابط</th><th className="p-2">النوع</th><th className="p-2">المصدر</th><th className="p-2">الحالة</th><th className="p-2">الإجراء</th></tr></thead><tbody>{visible.map(x=><tr key={x.id} className="border-b border-[var(--border-default)]/40"><td className="p-2 font-mono text-xs max-w-[390px] truncate" dir="ltr">{x.normalized_url}</td><td className="p-2 text-xs whitespace-nowrap">{typeText[x.link_type]||'واتساب'}</td><td className="p-2 text-xs">{value(x.source_group_name)}</td><td className="p-2"><Badge>{showStatus(x.status)}</Badge></td><td className="p-2 flex gap-1"><Button variant="outline" onClick={async()=>{await navigator.clipboard?.writeText(x.normalized_url);await action('copy',{ids:[x.id]})}} title="نسخ الرابط"><Copy className="w-3 h-3"/></Button><a href={x.normalized_url} target="_blank" rel="noreferrer" className="inline-flex items-center px-2 rounded-lg border"><ExternalLink className="w-3 h-3"/></a></td></tr>)}</tbody></table>{!visible.length&&<div className="text-center py-8 text-sm text-[var(--text-muted)]">لا توجد روابط حقيقية ضمن الفلتر الحالي</div>}</div></CardContent></Card><Card id="auto-activity"><CardContent className="p-5"><h2 className="font-bold flex gap-2 items-center mb-4"><Activity className="w-5 h-5 text-cyan-400"/>النشاط المباشر</h2><div className="space-y-2 max-h-[520px] overflow-auto">{events.map(e=><div key={e.id} className="text-xs border-b border-[var(--border-default)]/50 pb-2"><b className="text-cyan-400">{showStatus(e.event_type)}</b><span className="mx-2">{e.message}</span><span className="text-[var(--text-muted)]">{e.created_at?new Date(e.created_at).toLocaleTimeString('ar'):''}</span></div>)}{!events.length&&<div className="text-sm text-[var(--text-muted)]">لا توجد أحداث بعد</div>}</div></CardContent></Card></div></div>;
}
