import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Upload, Link2, Users, Play, Pause, Square, RefreshCw, FileText, CheckCircle2, XCircle, Clock3, Activity, Search } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { API, authFetch } from '@/utils/api';

type Account = { id:string; name:string; phone_number?:string; status?:string; health_status?:string; connected:boolean; last_activity_at?:string };
type FileRow = { id:string; file_name:string; total_links:number; valid_links:number; duplicate_links:number; invalid_links:number; processed_links:number; status:string; created_at:string };
type Job = { id:string; fileId:string; status:string; total:number; processed:number; successful:number; failed:number; skipped:number; accountIds:string[]; minDelay:number; maxDelay:number; startedAt:string; lastError?:string };
const statusLabel:Record<string,string> = { ready:'جاهز', running:'يعمل', paused:'متوقف مؤقتاً', completed:'مكتمل', stopped:'متوقف', error:'خطأ', pending:'قيد الانتظار', processing:'قيد المعالجة', success:'ناجح', failed:'فشل', skipped:'متخطى' };
const displayValue = (value: unknown, fallback = '—') => { if (value === null || value === undefined || value === '') return fallback; if (typeof value === 'object') { try { return JSON.stringify(value); } catch { return fallback; } } return String(value); };
const displayStatus = (value: unknown) => statusLabel[displayValue(value, '')] || displayValue(value, 'غير معروف');
const apiError = (value: unknown, fallback = 'حدث خطأ غير متوقع') => { const text = displayValue(value, ''); return text && text !== '[object Object]' ? text : fallback; };

export default function LinkImportView({ accountId, accounts: initialAccounts }:{accountId:string|null; accounts:Account[]}) {
  const [accountIdState,setAccountIdState]=useState(accountId||initialAccounts[0]?.id||'');
  useEffect(()=>{ if(accountId) setAccountIdState(accountId); },[accountId]);
  const [accounts,setAccounts]=useState<Account[]>(initialAccounts); const [files,setFiles]=useState<FileRow[]>([]); const [selectedFile,setSelectedFile]=useState<FileRow|null>(null);
  const [items,setItems]=useState<any[]>([]); const [selectedAccounts,setSelectedAccounts]=useState<string[]>([]); const [minDelay,setMinDelay]=useState(30); const [maxDelay,setMaxDelay]=useState(60); const [job,setJob]=useState<Job|null>(null); const [search,setSearch]=useState(''); const [message,setMessage]=useState(''); const fileRef=useRef<HTMLInputElement>(null);
  const load=useCallback(async()=>{ if(!accountIdState)return; try { const [f,a]=await Promise.all([authFetch(`${API}/links/import/files?accountId=${accountIdState}`),authFetch(`${API}/links/import/accounts`)]); const fd=await f.json(); const ad=await a.json(); if(fd.success)setFiles(Array.isArray(fd.files)?fd.files:[]); if(ad.success)setAccounts(Array.isArray(ad.accounts)?ad.accounts:[]); } catch (error) { setMessage(apiError(error,'تعذر تحديث بيانات نظام الاستيراد')); } },[accountIdState]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{ if(!job||!['running','paused'].includes(displayValue(job.status,'')))return; const t=setInterval(async()=>{try { const r=await authFetch(`${API}/links/import/jobs/${job.id}?accountId=${accountIdState}`); const d=await r.json(); if(d.job&&typeof d.job==='object')setJob(d.job); if(['completed','stopped','error'].includes(displayValue(d.job?.status,'')))load(); } catch(error) { setMessage(apiError(error,'تعذر تحديث حالة العملية')); }},1500); return()=>clearInterval(t)},[job,accountIdState,load]);
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0]; if(!f)return; if(!/\.(txt|csv|json|docx)$/i.test(f.name)){setMessage('يسمح برفع ملفات TXT أو CSV أو JSON أو Microsoft Word DOCX فقط');return} const isDocx=/\.docx$/i.test(f.name); let content=''; let encoding='text'; if(isDocx){const buffer=await f.arrayBuffer(); let binary=''; const bytes=new Uint8Array(buffer); for(let i=0;i<bytes.length;i+=0x8000) binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000)); content=btoa(binary); encoding='base64';}else content=await f.text(); try { const r=await authFetch(`${API}/links/import/files`,{method:'POST',body:JSON.stringify({accountId:accountIdState,fileName:f.name,content,encoding})}); const d=await r.json(); if(!r.ok||!d.success) throw new Error(apiError(d.error,'تعذر استيراد الملف')); if(d.file){setSelectedFile(d.file);setItems(Array.isArray(d.preview)?d.preview:[]);} setMessage(`تم تحليل ${d.file?.valid_links||0} رابط صالح من الملف`); load(); } catch(error) { setMessage(apiError(error,'تعذر استيراد الملف')); } finally { e.target.value=''; } };
  const selectFile=async(f:FileRow)=>{setSelectedFile(f); try { const r=await authFetch(`${API}/links/import/files/${f.id}?accountId=${accountIdState}`); const d=await r.json(); if(!r.ok||!d.success) throw new Error(apiError(d.error,'تعذر عرض روابط الملف')); setItems(Array.isArray(d.items)?d.items:[]); } catch(error) { setItems([]); setMessage(apiError(error,'تعذر عرض روابط الملف')); }};
  const start=async()=>{if(!selectedFile||!selectedAccounts.length)return setMessage('اختر ملفاً وحساباً متصلاً واحداً على الأقل'); try { const r=await authFetch(`${API}/links/import/start`,{method:'POST',body:JSON.stringify({accountId:accountIdState,fileId:selectedFile.id,accountIds:selectedAccounts,minDelay,maxDelay,distributionMode:'round_robin'})}); const d=await r.json(); if(!r.ok||!d.success) throw new Error(apiError(d.error,'تعذر بدء العملية')); if(!d.job||typeof d.job!=='object') throw new Error('استجابة بدء العملية غير صالحة'); setJob(d.job); setMessage('بدأت العملية الفعلية'); } catch(error) { setMessage(apiError(error,'تعذر بدء العملية')); }};
  const control=async(action:string)=>{if(!job)return; try { const r=await authFetch(`${API}/links/import/jobs/${job.id}/${action}`,{method:'POST',body:JSON.stringify({accountId:accountIdState})}); const d=await r.json(); if(!r.ok||!d.success) throw new Error(apiError(d.error,'تعذر تنفيذ الإجراء')); if(d.job&&typeof d.job==='object')setJob(d.job); } catch(error) { setMessage(apiError(error,'تعذر تنفيذ الإجراء')); }};
  const visibleItems=useMemo(()=>items.filter(x=>!search||x.url?.toLowerCase().includes(search.toLowerCase())),[items,search]);
  const pct=job?.total?Math.round(job.processed/job.total*100):0;
  return <div dir="rtl" className="p-5 md:p-8 space-y-6 max-w-[1600px] mx-auto"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-3"><div className="rounded-2xl bg-emerald-500/15 p-3 text-emerald-400"><Link2/></div><div><h1 className="text-2xl font-extrabold">نظام استيراد الروابط</h1><p className="text-sm text-[var(--text-muted)] mt-1">استيراد ملفات واردة بصيغ TXT وCSV وJSON وMicrosoft Word وتشغيل انضمام مراقب بالحسابات المتصلة فعلياً</p></div></div></div><div className="flex gap-2"><input ref={fileRef} type="file" accept=".txt,.csv,.json,.docx,text/plain,text/csv,application/json,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="hidden" onChange={upload}/><Button onClick={()=>fileRef.current?.click()}><Upload className="w-4 h-4 ml-2"/>استيراد ملفات واردة</Button><Button variant="outline" onClick={load}><RefreshCw className="w-4 h-4 ml-2"/>تحديث</Button></div></div>
  {message&&<div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{message}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[['الملفات',files.length,FileText],['الروابط',selectedFile?.total_links||0,Link2],['الصالحة',selectedFile?.valid_links||0,CheckCircle2],['غير الصالحة',selectedFile?.invalid_links||0,XCircle],['نسبة التقدم',`${pct}%`,Activity]].map(([label,value,Icon]:any)=><Card key={label}><CardContent className="p-4"><div className="flex justify-between text-xs text-[var(--text-muted)]"><span>{label}</span><Icon className="w-4 h-4"/></div><div className="text-2xl font-bold mt-2">{value}</div></CardContent></Card>)}</div>
  <div className="grid xl:grid-cols-[1.35fr_1fr] gap-5"><Card><CardContent className="p-5"><div className="flex items-center justify-between mb-4"><h2 className="font-bold flex items-center gap-2"><FileText className="w-5 h-5 text-emerald-400"/>الملفات المستوردة</h2><span className="text-xs text-[var(--text-muted)]">اختر ملفاً للمعاينة والتشغيل</span></div><div className="space-y-2">{files.map(f=><button key={f.id} onClick={()=>selectFile(f)} className={`w-full text-right rounded-xl border p-3 transition ${selectedFile?.id===f.id?'border-emerald-500 bg-emerald-500/10':'border-[var(--border-default)] hover:border-emerald-500/50'}`}><div className="flex items-center justify-between"><span className="font-semibold">{f.file_name}</span><Badge>{displayStatus(f.status)}</Badge></div><div className="text-xs text-[var(--text-muted)] mt-2">{f.valid_links} صالح · {f.duplicate_links} مكرر · {f.invalid_links} غير صالح · {f.processed_links||0} تمت معالجته</div></button>)}{!files.length&&<div className="text-center py-10 text-sm text-[var(--text-muted)]">لم يتم استيراد ملفات بعد</div>}</div></CardContent></Card>
  <Card><CardContent className="p-5"><h2 className="font-bold flex items-center gap-2 mb-4"><Users className="w-5 h-5 text-emerald-400"/>الحسابات الجاهزة للعمل</h2><div className="space-y-2 max-h-72 overflow-auto">{accounts.map(a=><label key={a.id} className={`flex items-center gap-3 rounded-xl border p-3 ${a.connected?'cursor-pointer':'opacity-50 cursor-not-allowed'}`}><input type="checkbox" disabled={!a.connected} checked={selectedAccounts.includes(a.id)} onChange={e=>setSelectedAccounts(x=>e.target.checked?[...x,a.id]:x.filter(id=>id!==a.id))}/><span className={`w-2 h-2 rounded-full ${a.connected?'bg-emerald-400':'bg-red-400'}`}/><span className="flex-1"><b>{a.name}</b><small className="block text-xs text-[var(--text-muted)]">{a.phone_number||'رقم مخفي'} · {a.connected?'متصل وجاهز':'غير متصل'}</small></span></label>)}</div><div className="grid grid-cols-2 gap-3 mt-4"><label className="text-xs">الحد الأدنى (ث)<input type="number" min="0" value={minDelay} onChange={e=>setMinDelay(+e.target.value)} className="mt-1 w-full rounded-lg bg-[var(--bg-elevated)] p-2"/></label><label className="text-xs">الحد الأقصى (ث)<input type="number" min="0" value={maxDelay} onChange={e=>setMaxDelay(+e.target.value)} className="mt-1 w-full rounded-lg bg-[var(--bg-elevated)] p-2"/></label></div><div className="flex flex-wrap gap-2 mt-4"><Button onClick={start} disabled={!selectedFile||!selectedAccounts.length||!!job&&['running','paused'].includes(job.status)}><Play className="w-4 h-4 ml-2"/>بدء العملية</Button>{job&&<><Button variant="outline" onClick={()=>control(job.status==='paused'?'resume':'pause')}><Pause className="w-4 h-4 ml-2"/>{job.status==='paused'?'استئناف':'إيقاف مؤقت'}</Button><Button variant="outline" onClick={()=>control('stop')}><Square className="w-4 h-4 ml-2"/>إيقاف نهائي</Button></>}</div></CardContent></Card></div>
  {job&&<Card><CardContent className="p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">مراقبة العملية <span className="text-xs text-emerald-400 mr-2">{displayStatus(job.status)}</span></h2><p className="text-xs text-[var(--text-muted)] mt-1">{job.processed} من {job.total} · ناجح {job.successful} · فاشل {job.failed} · متخطى {job.skipped}</p></div><div className="text-2xl font-bold text-emerald-400">{pct}%</div></div><div className="h-2 bg-[var(--bg-elevated)] rounded-full mt-4 overflow-hidden"><div className="h-full bg-emerald-500 transition-all" style={{width:`${pct}%`}}/></div></CardContent></Card>}
  <Card><CardContent className="p-5"><div className="flex flex-wrap items-center justify-between gap-3 mb-4"><h2 className="font-bold">معاينة الروابط وسجل الحالة</h2><div className="relative"><Search className="w-4 h-4 absolute right-2 top-2.5 text-[var(--text-muted)]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث داخل الروابط" className="rounded-lg bg-[var(--bg-elevated)] py-2 pr-8 pl-3 text-sm"/></div></div><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-right text-[var(--text-muted)] border-b border-[var(--border-default)]"><th className="p-2">#</th><th className="p-2">الرابط</th><th className="p-2">الحالة</th><th className="p-2">الحساب</th><th className="p-2">النتيجة</th></tr></thead><tbody>{visibleItems.map((x,i)=><tr key={x.id||x.index||i} className="border-b border-[var(--border-default)]/50"><td className="p-2">{x.index||i+1}</td><td className="p-2 font-mono text-xs max-w-[420px] truncate" dir="ltr">{x.url}</td><td className="p-2"><Badge>{displayStatus(x.status)}</Badge></td><td className="p-2 text-xs">{x.assigned_account_id||'—'}</td><td className="p-2 text-xs max-w-[280px] truncate" title={displayValue(x.result)}>{displayValue(x.result)}</td></tr>)}</tbody></table>{!visibleItems.length&&<div className="text-center py-8 text-sm text-[var(--text-muted)]">اختر ملفاً لعرض الروابط</div>}</div></CardContent></Card></div>;
}
