import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { io } from 'socket.io-client';
import { Search, Plus, Trash2, MessageCircle, Activity, Users, Radio, Send, RefreshCw, X, CheckCircle2, WifiOff, Filter, CheckSquare } from 'lucide-react';
import { API, authFetch, TOKEN_KEY, USER_KEY } from '@/utils/api';
import { useToast } from '@/components/ui/ToastProvider';

const json = async (res: Response) => { const body = await res.json().catch(() => ({})); if (!res.ok || body.success === false) throw new Error(body.error || 'حدث خطأ'); return body; };

type Account = { id:string; name:string; phone_number?:string; username?:string; status:string; last_activity_at?:string; keyword_status?:string };
type Keyword = { id:string; keyword:string; match_mode:string; case_sensitive:boolean; normalize_arabic:boolean; account_ids:any; is_active:boolean };
type Result = { id:string; keyword:string; keyword_id:string; account_name:string; account_phone?:string; telegram_account_id:string; chat_title?:string; chat_id:string; message_id:string; sender_id?:string; sender_access_hash?:string; sender_first_name?:string; sender_last_name?:string; sender_name?:string; sender_username?:string; sender_phone?:string; message_text:string; message_timestamp?:string; reply_status:string };

export default function TelegramKeywordView(){
 const { addToast } = useToast();
 const [accounts,setAccounts]=useState<Account[]>([]); const [keywords,setKeywords]=useState<Keyword[]>([]); const [results,setResults]=useState<Result[]>([]); const [stats,setStats]=useState({total:0,today:0,active:0});
 const [loading,setLoading]=useState(true); const [connected,setConnected]=useState(false); const [search,setSearch]=useState(''); const [keywordFilter,setKeywordFilter]=useState('');
 const [modal,setModal]=useState(false); const [editing,setEditing]=useState<Keyword|null>(null); const [reply,setReply]=useState<Result|null>(null); const [replyText,setReplyText]=useState(''); const [openingId,setOpeningId]=useState<string|null>(null);
 const [form,setForm]=useState({keyword:'',match_mode:'contains',case_sensitive:false,normalize_arabic:true,search_groups:true,search_channels:true,account_ids:[] as string[]});
 const load=useCallback(async()=>{ try { const d=await json(await authFetch(`${API}/telegram-keywords/dashboard?limit=100&search=${encodeURIComponent(search)}${keywordFilter?`&keyword_id=${keywordFilter}`:''}`)); setAccounts(d.accounts||[]);setKeywords(d.keywords||[]);setResults(d.results||[]);setStats(d.stats||{total:0,today:0,active:0}); } catch(e:any){ addToast(e.message||'تعذر تحميل القسم','error'); } finally { setLoading(false); } },[search,keywordFilter,addToast]);
 useEffect(()=>{load();const timer=window.setInterval(load,15000);const socket=io(window.location.origin,{path:'/socket.io',transports:['websocket','polling'],reconnection:true}); const user=JSON.parse(localStorage.getItem(USER_KEY)||'{}'); const join=()=>{setConnected(true);socket.emit('join_user',{userId:user.id,token:localStorage.getItem(TOKEN_KEY)||''});}; socket.on('connect',join); socket.on('disconnect',()=>setConnected(false)); socket.on('telegram:keyword:matched',(p:any)=>{ if(p?.result){setResults(r=>[p.result,...r.filter(x=>x.id!==p.result.id)]);setStats(s=>({...s,total:s.total+1,today:s.today+1,active:s.active+1})); addToast(`تم اكتشاف كلمة: ${p.keyword?.keyword||''}`,'success');} }); return()=>{window.clearInterval(timer);socket.disconnect();};},[load,addToast]);
 const openCreate=()=>{setEditing(null);setForm({keyword:'',match_mode:'contains',case_sensitive:false,normalize_arabic:true,search_groups:true,search_channels:true,account_ids:[]});setModal(true);};
 const normalizeAccountIds=(value:any):string[]=>{if(Array.isArray(value))return value.map(String);if(typeof value==='string'){try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed.map(String):[];}catch{return [];}}return [];};
 const openEdit=(k:Keyword)=>{setEditing(k);setForm({keyword:k.keyword,match_mode:k.match_mode,case_sensitive:k.case_sensitive,normalize_arabic:k.normalize_arabic,search_groups:k.search_groups!==false,search_channels:k.search_channels!==false,account_ids:normalizeAccountIds(k.account_ids)});setModal(true);};
 const toggleAllAccounts=()=>setForm(f=>({...f,account_ids:f.account_ids.length===accounts.length?[]:accounts.map(a=>a.id)}));
 const save=async()=>{try{const d=await json(await authFetch(editing?`${API}/telegram-keywords/${editing.id}`:`${API}/telegram-keywords`,{method:editing?'PUT':'POST',body:JSON.stringify(form)}));addToast('تم حفظ الكلمة وتفعيلها','success');setModal(false);await load();}catch(e:any){addToast(e.message,'error');}};
 const remove=async(id:string)=>{if(!confirm('هل تريد حذف الكلمة المفتاحية؟'))return;try{await json(await authFetch(`${API}/telegram-keywords/${id}`,{method:'DELETE'}));addToast('تم حذف الكلمة','success');load();}catch(e:any){addToast(e.message,'error');}};
 const openDirectChat=async(result:Result)=>{if(openingId)return;setOpeningId(result.id);try{const d=await json(await authFetch(`${API}/telegram-keywords/results/${result.id}/open`,{method:'POST'}));if(!d.directLink)throw new Error('لم يتم إنشاء رابط موثوق للمحادثة الخاصة');window.open(d.directLink,'_blank','noopener,noreferrer');addToast('تم فتح المحادثة الخاصة مع صاحب الرسالة','success');}catch(e:any){addToast(e.message||'تعذر فتح المحادثة الخاصة','error');}finally{setOpeningId(null);}};
 const sendReply=async()=>{if(!reply||!replyText.trim())return;try{await json(await authFetch(`${API}/telegram-keywords/results/${reply.id}/reply`,{method:'POST',body:JSON.stringify({text:replyText})}));addToast('تم إرسال الرد الخاص عبر الحساب المصدر','success');setReply(null);setReplyText('');load();}catch(e:any){addToast(e.message,'error');}};
 const activeAccounts=useMemo(()=>accounts.filter(a=>a.status==='connected'),[accounts]);
 return <div dir="rtl" className="space-y-6 pb-10">
  <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-sky-500 to-indigo-600 flex items-center justify-center text-white shadow-lg"><Search size={24}/></div><div><h1 className="text-2xl font-bold">كلمات مفتاحية تيليجرام</h1><p className="text-sm text-[var(--text-muted)]">مراقبة حقيقية للرسائل من الحسابات المرتبطة</p></div></div></div><div className="flex gap-2"><button onClick={load} className="px-4 py-2 rounded-xl border border-[var(--border-default)] flex items-center gap-2"><RefreshCw size={16}/> تحديث</button><button onClick={openCreate} className="px-4 py-2 rounded-xl bg-[var(--brand-primary)] text-white flex items-center gap-2"><Plus size={17}/> إضافة كلمة مفتاحية</button></div></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Stat icon={<Users/>} title="الحسابات" value={accounts.length}/><Stat icon={<Radio/>} title="المتصلة" value={activeAccounts.length}/><Stat icon={<Search/>} title="الكلمات النشطة" value={keywords.filter(k=>k.is_active).length}/><Stat icon={<MessageCircle/>} title="النتائج" value={stats.total}/></div>
  <div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-card)] p-4"><div className="flex items-center justify-between mb-4"><h2 className="font-bold flex items-center gap-2"><Users size={18}/> حسابات تيليجرام المرتبطة</h2><span className={`text-xs px-2 py-1 rounded-full ${connected?'bg-emerald-500/15 text-emerald-400':'bg-amber-500/15 text-amber-400'}`}>{connected?'تحديث لحظي متصل':'جاري الاتصال'}</span></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{accounts.map(a=><div key={a.id} className="rounded-xl border border-[var(--border-default)] p-4"><div className="flex justify-between"><div><p className="font-semibold">{a.name}</p><p className="text-xs text-[var(--text-muted)]">{a.phone_number||'رقم غير متاح'}</p></div>{a.status==='connected'?<CheckCircle2 className="text-emerald-400" size={20}/>:<WifiOff className="text-rose-400" size={20}/>}</div><p className={`mt-3 text-xs ${a.status==='connected'?'text-emerald-400':'text-rose-400'}`}>{a.status==='connected'?'متصل ويعمل فعلياً':'غير متصل أو يحتاج جلسة صالحة'}</p><p className="text-[11px] text-[var(--text-muted)] mt-1">آخر نشاط: {a.last_activity_at?new Date(a.last_activity_at).toLocaleString('ar'): 'لا يوجد'}</p></div>)}{!accounts.length&&!loading&&<p className="text-sm text-[var(--text-muted)]">لا توجد حسابات تيليجرام مرتبطة بعد.</p>}</div></div>
  <div className="grid lg:grid-cols-[360px_1fr] gap-5"><div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-card)] p-4"><div className="flex justify-between items-center mb-4"><h2 className="font-bold">الكلمات المفتاحية</h2><button onClick={openCreate} className="p-2 rounded-lg bg-[var(--brand-primary)] text-white"><Plus size={16}/></button></div>{keywords.map(k=><div key={k.id} className="p-3 mb-2 rounded-xl border border-[var(--border-default)] hover:border-[var(--brand-primary)]"><div className="flex justify-between items-center"><span className="font-semibold">{k.keyword}</span><span className="text-[10px] text-emerald-400">{k.is_active?'نشطة':'متوقفة'}</span></div><p className="text-xs text-[var(--text-muted)] mt-1">مطابقة: {k.match_mode==='contains'?'احتواء':k.match_mode==='exact'?'كاملة':k.match_mode}</p><div className="flex gap-2 mt-3"><button onClick={()=>openEdit(k)} className="text-xs px-2 py-1 rounded bg-[var(--bg-elevated)]">تعديل</button><button onClick={()=>remove(k.id)} className="text-xs px-2 py-1 rounded bg-rose-500/10 text-rose-400"><Trash2 size={13}/></button></div></div>)}{!keywords.length&&<p className="text-sm text-[var(--text-muted)]">أضف أول كلمة لبدء المراقبة.</p>}</div>
  <div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-card)] p-4"><div className="flex flex-col md:flex-row gap-3 mb-4"><div className="relative flex-1"><Search className="absolute right-3 top-3 text-[var(--text-muted)]" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث في الرسائل والمجموعات والمرسلين..." className="w-full pr-10 pl-3 py-2 rounded-xl bg-[var(--bg-elevated)] border border-[var(--border-default)]"/></div><select value={keywordFilter} onChange={e=>setKeywordFilter(e.target.value)} className="px-3 py-2 rounded-xl bg-[var(--bg-elevated)] border border-[var(--border-default)]"><option value="">كل الكلمات</option>{keywords.map(k=><option key={k.id} value={k.id}>{k.keyword}</option>)}</select><Filter size={18} className="hidden md:block mt-3 text-[var(--text-muted)]"/></div>{results.map(r=><div key={r.id} className="p-4 mb-3 rounded-xl border border-[var(--border-default)]"><div className="flex flex-col md:flex-row md:items-start justify-between gap-2"><div><div className="flex flex-wrap gap-2 items-center"><span className="font-bold text-sky-400">{r.keyword}</span><span className="text-xs text-[var(--text-muted)]">{r.chat_title||r.chat_id}</span><span className="text-xs text-[var(--text-muted)]">عبر: {r.account_name}</span></div><p className="mt-2 leading-7">{r.message_text}</p><p className="text-xs text-[var(--text-muted)] mt-2">المرسل: {r.sender_name||'غير متاح'} {r.sender_username?`@${r.sender_username.replace(/^@/,'')}`:''} {r.sender_phone||' — الرقم غير متاح'}</p><p className="text-[11px] text-[var(--text-muted)] mt-1">معرّف Telegram: {r.sender_id||'غير محفوظ — لا يمكن فتح محادثة موثوقة'}</p></div><button onClick={()=>openDirectChat(r)} disabled={openingId!==null} className="shrink-0 px-3 py-2 rounded-lg bg-[var(--brand-primary)] disabled:opacity-60 text-white text-sm flex items-center gap-2">{openingId===r.id?<><RefreshCw size={15} className="animate-spin"/> جاري فتح المحادثة...</>:<><MessageCircle size={15}/> رد مباشر</>}</button></div></div>)}{!results.length&&!loading&&<div className="py-16 text-center text-[var(--text-muted)]"><Activity className="mx-auto mb-3"/><p>لا توجد نتائج مكتشفة بعد من Telegram الحقيقي.</p></div>}</div></div>
  {modal&&<div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-2xl bg-[var(--bg-card)] border border-[var(--border-default)] p-5"><div className="flex justify-between items-center mb-5"><h3 className="font-bold text-lg">{editing?'تعديل كلمة مفتاحية':'إضافة كلمة مفتاحية'}</h3><button onClick={()=>setModal(false)}><X/></button></div><input value={form.keyword} onChange={e=>setForm({...form,keyword:e.target.value})} placeholder="الكلمة أو العبارة" className="w-full p-3 rounded-xl bg-[var(--bg-elevated)] border border-[var(--border-default)] mb-3"/><select value={form.match_mode} onChange={e=>setForm({...form,match_mode:e.target.value})} className="w-full p-3 rounded-xl bg-[var(--bg-elevated)] border border-[var(--border-default)] mb-3"><option value="contains">تحتوي على</option><option value="exact">مطابقة كاملة</option><option value="starts_with">تبدأ بـ</option><option value="ends_with">تنتهي بـ</option><option value="regex">Regex</option></select><div className="space-y-2 mb-4">{[['case_sensitive','حساس لحالة الأحرف'],['normalize_arabic','تطبيع عربي ذكي'],['search_groups','البحث في المجموعات'],['search_channels','البحث في القنوات']].map(([key,label])=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean((form as any)[key])} onChange={e=>setForm({...form,[key]:e.target.checked})}/>{label}</label>)}</div><div className="flex items-center justify-between mb-2"><p className="text-sm font-semibold">الحسابات المستخدمة</p><button type="button" onClick={toggleAllAccounts} className="text-xs px-3 py-1.5 rounded-lg bg-sky-500/10 text-sky-300 hover:bg-sky-500/20 flex items-center gap-1"><CheckSquare size={14}/>{form.account_ids.length===accounts.length&&accounts.length>0?'إلغاء تحديد الكل':'تحديد كل الحسابات'}</button></div><div className="max-h-32 overflow-auto space-y-2 mb-5">{accounts.map(a=><label key={a.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.account_ids.includes(a.id)} onChange={e=>setForm({...form,account_ids:e.target.checked?[...form.account_ids,a.id]:form.account_ids.filter(id=>id!==a.id)})}/>{a.name} <span className="text-xs text-[var(--text-muted)]">({a.status})</span></label>)}</div><button onClick={save} className="w-full py-3 rounded-xl bg-[var(--brand-primary)] text-white font-semibold">حفظ وتفعيل</button></div></div>}
  {reply&&<div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-2xl bg-[var(--bg-card)] border border-[var(--border-default)] p-5"><div className="flex justify-between items-center mb-4"><h3 className="font-bold">الرد عبر {reply.account_name}</h3><button onClick={()=>setReply(null)}><X/></button></div><p className="text-sm text-[var(--text-muted)] mb-3">{reply.chat_title||reply.chat_id} — {reply.sender_name||'مرسل غير معروف'}</p><textarea value={replyText} onChange={e=>setReplyText(e.target.value)} placeholder="اكتب الرد هنا..." rows={5} className="w-full p-3 rounded-xl bg-[var(--bg-elevated)] border border-[var(--border-default)] mb-4"/><button onClick={sendReply} className="w-full py-3 rounded-xl bg-[var(--brand-primary)] text-white flex justify-center items-center gap-2"><Send size={16}/> إرسال عبر الحساب المصدر</button></div></div>}
 </div>;
}
function Stat({icon,title,value}:{icon:React.ReactNode;title:string;value:number}){return <div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-card)] p-4"><div className="text-sky-400 mb-2">{icon}</div><p className="text-xs text-[var(--text-muted)]">{title}</p><p className="text-2xl font-bold mt-1">{value}</p></div>}
